// Image imports (lib/marketing/shots.ts) are typed by next's own declarations. next-env.d.ts
// carries the same reference but is generated by `next build` and not tracked, so a type check
// that runs before a build (CI) needs it here.
/// <reference types="next/image-types/global" />
