/**
 * The translation registry's rows for the product's own translations (engagement P1.1, D-127).
 *
 *   npm run -s i18n:registry > registry.sql && psql "$DATABASE_URL" -f registry.sql
 *
 * Writes SQL that upserts, for English:
 *   - the core statements (messages/en.json factor.<key>.s<n>) as core:<key>:<n>;
 *   - the questions outside the index and their options (extra.<key>.text, .o<n>);
 *   - the module items and their options, from app.module_items' own English (0072).
 *   - a worded module's variants (module:<uuid>:v:barnehage, :v:skole) from its "en.<wording>".
 * Every row is source 'machine' and a draft (0084): the product's English was written with AI
 * assistance, and approving it (Admin › Juridisk, public.admin_translations_approve) is the
 * human review. A new text for an approved row is a new version, a draft again; the approved
 * one stays in app.item_translation_log, and in every round it was pinned in. Idempotent.
 *
 * Only English has messages to take translations from; Polish and Lithuanian rows come from a
 * translator, or, on the QA tenant only, from scripts/qa/seed.mjs as qa-fixture rows.
 */
import { readFileSync } from 'node:fs'

const en = JSON.parse(readFileSync('messages/en.json', 'utf8'))
const lit = (s) => `'${String(s).replace(/'/g, "''")}'`
const rows = []

for (const [factor, f] of Object.entries(en.factor)) {
  for (const [k, v] of Object.entries(f)) {
    const m = /^s(\d+)$/.exec(k)
    if (m) rows.push([`core:${factor}:${m[1]}`, v])
  }
}
for (const [key, x] of Object.entries(en.extra)) {
  rows.push([`extra:${key}`, x.text])
  for (const [k, v] of Object.entries(x)) {
    const m = /^o(\d+)$/.exec(k)
    if (m) rows.push([`extra:${key}:o${m[1]}`, v])
  }
}

const upsert = `on conflict (item_id, locale) do update set text = excluded.text where app.item_translations.text is distinct from excluded.text`
console.log('-- generated by scripts/i18n/registry-seed.mjs — do not edit')
console.log('begin;')
console.log(`insert into app.item_translations (item_id, locale, text, source) values`)
console.log(rows.map(([id, text]) => `  (${lit(id)}, 'en', ${lit(text)}, 'machine')`).join(',\n'))
console.log(`${upsert};`)
// only keys the registry can name: a core statement or extra that exists in the database
console.log(`delete from app.item_translations t where t.locale = 'en' and t.item_id like 'core:%'
  and not exists (select 1 from app.statements s where t.item_id = 'core:' || s.factor_key || ':' || s.ordinal);`)
console.log(`insert into app.item_translations (item_id, locale, text, source)
select 'module:' || i.id, 'en', i.text ->> 'en', 'machine' from app.module_items i where coalesce(i.text ->> 'en', '') <> ''
${upsert};`)
// a worded module's variants (0083, 0084): module:<uuid>:v:barnehage from its "en.barnehage"
console.log(`insert into app.item_translations (item_id, locale, text, source)
select 'module:' || i.id || ':v:' || w, 'en', i.text ->> ('en.' || w), 'machine'
from app.module_items i cross join unnest(array['barnehage', 'skole']) w where coalesce(i.text ->> ('en.' || w), '') <> ''
${upsert};`)
console.log(`insert into app.item_translations (item_id, locale, text, source)
select 'module:' || i.id || ':o' || y.n, 'en', y.o ->> 'en', 'machine'
from app.module_items i cross join lateral jsonb_array_elements(i.options) with ordinality as y(o, n)
where coalesce(y.o ->> 'en', '') <> ''
${upsert};`)
console.log('commit;')
