/**
 * The Teams app's two icons (0176, D-203), rendered from the product's own mark, app/icon.svg.
 *
 *   node scripts/teams/icons.mjs
 *
 * Writes teams-app/color.png (192 × 192, the mark on the app canvas, as app/apple-icon.png is drawn)
 * and teams-app/outline.png (32 × 32, the same frame and pulse glyph in white on transparent, as the
 * Teams manifest asks of an outline icon), and both as base64 in lib/teams/icons.ts for the
 * screen's download. Nothing is drawn that the mark does not have.
 */
import { chromium } from 'playwright-core'
import { existsSync, readFileSync, writeFileSync } from 'node:fs'

const svg = readFileSync('app/icon.svg', 'utf8').replace(/<!--[\s\S]*?-->/g, '')
const outline = svg.replaceAll('#191510', '#FFFFFF').replace('fill="#FFFDF6"', 'fill="none"')
const executablePath = ['/opt/pw-browsers/chromium', process.env.CHROMIUM].find((p) => p && existsSync(p))
const browser = await chromium.launch(executablePath ? { executablePath } : {})

async function render(source, size, background) {
  const page = await browser.newPage({ viewport: { width: size, height: size }, deviceScaleFactor: 1 })
  await page.setContent(
    `<html><body style="margin:0;background:${background ?? 'transparent'}">${source.replace(
      /width="32" height="32"/,
      `width="${size}" height="${size}"`,
    )}</body></html>`,
  )
  const png = await page.screenshot({ omitBackground: !background, clip: { x: 0, y: 0, width: size, height: size } })
  await page.close()
  return png
}

const color = await render(svg, 192, '#FCF6E9')
const line = await render(outline, 32)
writeFileSync('teams-app/color.png', color)
writeFileSync('teams-app/outline.png', line)
// the same bytes for the screen's download, so the server needs no file from outside its bundle
writeFileSync(
  'lib/teams/icons.ts',
  `// generated by scripts/teams/icons.mjs from app/icon.svg — do not edit\n` +
    `export const TEAMS_ICON_COLOR = '${color.toString('base64')}'\n` +
    `export const TEAMS_ICON_OUTLINE = '${line.toString('base64')}'\n`,
)
await browser.close()
console.log(`teams-app/color.png 192 px (${color.length} bytes), teams-app/outline.png 32 px (${line.length} bytes)`)
