/**
 * Builds and deploys the edge functions in supabase/functions. D-65.
 *
 *   node scripts/functions/deploy.mjs              generate, check, deploy both
 *   node scripts/functions/deploy.mjs --check      generate and type-check only
 *
 * The mail texts live in messages/<lang>.json under `mail`, like every other string, so
 * `npm run verify:i18n` holds them to parity. The functions cannot read that file at run
 * time, so this writes `supabase/functions/_shared/messages.gen.ts` from it before every
 * check and deploy; the generated file is not committed.
 *
 * Deploys through the Management API with SB_MCP_PAT (or SUPABASE_ACCESS_TOKEN) from the
 * environment. `verify_jwt` is off for both: the dispatcher authenticates its own secret,
 * and the Auth hook a Standard Webhooks signature.
 */
import { execFileSync } from 'node:child_process'
import { readFileSync, writeFileSync } from 'node:fs'

const REF = process.env.SUPABASE_PROJECT_REF ?? 'jmhhszsnjfqgclxzhciq'
const TOKEN = process.env.SB_MCP_PAT ?? process.env.SUPABASE_ACCESS_TOKEN
const FUNCTIONS = ['orgpuls-dispatch', 'orgpuls-auth-mail']
const SHARED = ['_shared/mail.ts', '_shared/brevo.ts', '_shared/messages.gen.ts']
const ROOT = 'supabase/functions'

const mail = (lang) => JSON.parse(readFileSync(`messages/${lang}.json`, 'utf8')).mail
writeFileSync(
  `${ROOT}/_shared/messages.gen.ts`,
  `// generated by scripts/functions/deploy.mjs from messages/*.json — do not edit\n` +
    `export const MAIL = ${JSON.stringify({ no: mail('no'), en: mail('en') }, null, 2)} as const\n`,
)

execFileSync('npx', ['-y', 'deno', 'check', '--config', `${ROOT}/deno.json`, ...FUNCTIONS.map((f) => `${ROOT}/${f}/index.ts`)], { stdio: 'inherit' })
if (process.argv.includes('--check')) process.exit(0)

if (!TOKEN) {
  console.error('SB_MCP_PAT (or SUPABASE_ACCESS_TOKEN) is not set; nothing deployed')
  process.exit(2)
}

for (const fn of FUNCTIONS) {
  const form = new FormData()
  form.append(
    'metadata',
    new Blob([JSON.stringify({ name: fn, entrypoint_path: `${fn}/index.ts`, verify_jwt: false })], { type: 'application/json' }),
  )
  for (const path of [`${fn}/index.ts`, ...SHARED]) {
    form.append('file', new Blob([readFileSync(`${ROOT}/${path}`)], { type: 'application/typescript' }), path)
  }
  const res = await fetch(`https://api.supabase.com/v1/projects/${REF}/functions/deploy?slug=${fn}`, {
    method: 'POST',
    headers: { Authorization: `Bearer ${TOKEN}` },
    body: form,
  })
  const body = await res.json().catch(() => ({}))
  if (!res.ok) {
    console.error(`${fn}: deploy failed, HTTP ${res.status}: ${JSON.stringify(body).slice(0, 400)}`)
    process.exit(1)
  }
  console.log(`${fn}: version ${body.version}, ${body.status}, verify_jwt ${body.verify_jwt}`)
}
