/**
 * npm run -s modules:seed [path…] > seed.sql — the registry rows for one or more module files.
 *
 * Validates each file with the module schema, hashes its canonical JSON, and prints one call
 * of app.module_seed(file, hash) per file, for psql (as the design fixture is applied). The
 * function decides what happens: a new version is written as a draft, the same content is
 * a no-op, a changed draft is replaced, and a published version with changed content is
 * refused — so running this twice, or on every deploy, is safe.
 *
 * Without arguments it seeds every file under modules/. Publishing is a separate, deliberate
 * step (modules:publish).
 */
import { canonicalJson, contentHash, parseModule } from '../../lib/modules/schema'
import { moduleFiles, readJson } from './files'

const paths = process.argv.slice(2).length ? process.argv.slice(2) : moduleFiles()
const out: string[] = ['-- generated by scripts/modules/seed.ts; do not edit', '\\set ON_ERROR_STOP on']
for (const path of paths) {
  const m = parseModule(readJson(path), path)
  const json = canonicalJson(m)
  if (json.includes('$module$')) throw new Error(`${path}: contains the quoting tag $module$`)
  out.push(`select '${m.module_id}@${m.version}' as module, app.module_seed($module$${json}$module$::jsonb, '${contentHash(m)}') as result;`)
}
console.log(out.join('\n'))
